
disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- identifier_name
- force_cast
- empty_parentheses_with_trailing_closure
- line_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

